package xdev.db.db2i.jdbc;

/*-
 * #%L
 * DB2i
 * %%
 * Copyright (C) 2003 - 2023 XDEV Software
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-3.0.html>.
 * #L%
 */


import xdev.db.DBException;
import xdev.db.jdbc.JDBCConnection;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;
public class DB2iJDBCConnection extends JDBCConnection<DB2iJDBCDataSource, DB2iDbms>
{
	public DB2iJDBCConnection(DB2iJDBCDataSource dataSource)
	{
		super(dataSource);
	}
	
	
	@Override
	protected Connection establishConnection() throws DBException
	{
		Connection con = super.establishConnection();
		
		try
		{
			String schema = dataSource.getSchema();
			if(schema != null && schema.length() > 0 && !schema.equals(dataSource.getUserName()))
			{
				con.createStatement().execute("SET SCHEMA " + schema); //$NON-NLS-1$
			}
		}
		catch(SQLException e)
		{
			throw new DBException(dataSource,e);
		}
		
		return con;
	}
	
	
	@Override
	public int getQueryRowCount(String select) throws DBException
	{
		StringBuilder sb = new StringBuilder();
		sb.append("SELECT COUNT(*) FROM ("); //$NON-NLS-1$
		sb.append(select);
		sb.append(")"); //$NON-NLS-1$
		
		try
		{
			ResultSet result = queryJDBC(sb.toString());
			try
			{
				result.next();
				int rowCount = result.getInt(1);
				return rowCount;
			}
			finally
			{
				result.close();
			}
		}
		catch(DBException e)
		{
			throw e;
		}
		catch(Exception e)
		{
			throw new DBException(dataSource,e);
		}
	}
	
	
	@Override
	public void createTable(String tableName, String primaryKey, Map<String, String> columnMap,
			boolean isAutoIncrement, Map<String, String> foreignKeys) throws Exception
	{
		Connection connection = super.getConnection();
		Statement statement = connection.createStatement();
		try
		{
			if(!checkIfTableExists(connection.createStatement(),tableName))
			{
				if(!columnMap.containsKey(primaryKey))
				{
					columnMap.put(primaryKey,"INTEGER"); //$NON-NLS-1$
				}
				StringBuffer createStatement = null;
				
				if(isAutoIncrement)
				{
					createStatement = new StringBuffer(
							"CREATE TABLE IF NOT EXISTS " + tableName + "(" //$NON-NLS-1$ //$NON-NLS-2$
									+ primaryKey
									+ " " + columnMap.get(primaryKey) + " GENERATED BY Default AS IDENTITY(Start with 201, Increment by 1) PRIMARY KEY,"); //$NON-NLS-1$ //$NON-NLS-2$
				}
				else
				{
					createStatement = new StringBuffer(
							"CREATE TABLE IF NOT EXISTS " + tableName + "(" //$NON-NLS-1$ //$NON-NLS-2$
									+ primaryKey + " " + columnMap.get(primaryKey) + ","); //$NON-NLS-1$ //$NON-NLS-2$
				}
				
				int i = 0;
				for(String keySet : columnMap.keySet())
				{
					if(!keySet.equals(primaryKey))
					{
						if(i <= columnMap.size())
						{
							createStatement.append(keySet + " " + columnMap.get(keySet) + ","); //$NON-NLS-1$ //$NON-NLS-2$
							
						}
						else
						{
							createStatement.append(keySet + " " + columnMap.get(keySet) + ")"); //$NON-NLS-1$ //$NON-NLS-2$
							
						}
						
						i++;
					}
				}
				
				if(log.isDebugEnabled())
				{
					log.debug("SQL Statement to create a table: " + createStatement.toString()); //$NON-NLS-1$
				}
				
				statement.execute(createStatement.toString());
			}
		}
		catch(Exception e)
		{
			throw e;
		}
		finally
		{
			statement.close();
			connection.close();
		}
	}
	
	
	private boolean checkIfTableExists(Statement statement, String tableName) throws Exception
	{
		
		String sql = "SELECT NAME FROM SYSIBM.SYSTABLES WHERE NAME='" + tableName + "'"; //$NON-NLS-1$ //$NON-NLS-2$
		
		ResultSet resultSet = null;
		try
		{
			statement.execute(sql);
			resultSet = statement.getResultSet();
		}
		catch(Exception e)
		{
			if(resultSet != null)
			{
				resultSet.close();
			}
			statement.close();
			throw e;
		}
		
		if(resultSet != null)
		{
			if(resultSet.next())
			{
				resultSet.close();
				statement.close();
				return true;
			}
			resultSet.close();
			
		}
		statement.close();
		return false;
	}
	
}
